<?php

return [
    'words' => [
        'idiot',
        'budalla',
        'maskara',
        'i paaftë',
        'e paaftë',
        'rrugac',
        'rrugace',
        'vrasës',
        'vrasëse',
        'do të vras',
        'do të të rrah',
        'plehrë',
        'racist',
        'raciste',
        'zezak',
        'zezake',
        'cigan',
        'cigane',
        'terrorist',
        'terroriste',
        'seksist',
        'seksiste',
        'gënjeshtar',
        'gënjeshtare',
        'mashtrues',
        'mashtruese',
        'i neveritshëm',
        'e neveritshme',
        'psikopat',
        'psikopate',
        'hajdut',
        'hajdute',
        'bastard',
        'bastarde',
        'kafshë',
        'i paditur',
        'e paditur',
        'fool',
        'killer',
        'I will kill',
        'I will beat',
        'trash',
        'black',
        'gypsy',
        'negro',
        'liar',
        'psychopath',
        'thief',
        'sexist',
    ],
];
